### ISSUE TITLE
Make accounts optional

### ISSUE THREAD

**Issue by TitanNano** [schmuckli-dev/wallet#4]
I'm curious about your application, but not interested in creating an account. If creating an account would be optional, I would be willing to give it a try and might create an account later.

**Comment by julianschmuckli** [comment]
Hi @TitanNano,

thank you for your suggestion. I have now implemented on the login section a button where you can try out the full version of the app without login. If you consider in the future to create an account, you can migrate the existing session in the settings to a fully functional login.

Best regards
Julian
